export const FUEL_EU_CONSTANTS = {
    TARGET_INTENSITY_2025: 89.3368,
    BASE_INTENSITY_2020: 91.16,
    ENERGY_DENSITY_MJ_PER_TON: 41000,
    COMPLIANCE_THRESHOLD: 0,
    POOL_RULES: {
      DEFICIT_SHIP_NOT_WORSE: true,
      SURPLUS_SHIP_NOT_NEGATIVE: true,
    },
  };
  